name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1.1.1
        with: 
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          create_credentials_file: true
          access_token_lifetime: '300s'  
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.1.1

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"

      # Step 3: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 4: Deploy Infrastructure using Terraform
      - name: Deploy Infrastructure
        run: terraform apply -auto-approve