name: Zip Cloud Function
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            # Add your build steps here
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create zip file
              run: |
                    cd cloud_function
                    zip source.zip main.py requirements.txt
                    mv source.zip ../
                    cd ..
                    echo "Zip file created"
            - name: Google Auth
              id: auth
              uses: google-github-actions/auth@v1.1.1
              with: 
                workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
                service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
                create_credentials_file: true
                access_token_lifetime: '300s'

            - name: Set up gcloud Cloud SDK environment
              uses: google-github-actions/setup-gcloud@v1.1.1
                        


